# Part 1 : Introduction 

In [1]:
'''
____________Author_____________
Nazanin Mohammadrezaei

__________ Resource ___________
Sentdex YouTube channel

___________ Playlist __________
Deep Learning and Neural Networks using PyTorch

___________ Video ____________
Part 1 : introduction

'''  

import torch
import numpy as np
import torchvision
from torchvision import transforms, datasets
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.nn.functional as F


# introduction to tensors
x = torch.Tensor([2, 5])
y = torch.Tensor([3, 3])
z = np.zeros([2,3])
a = x.shape
b = torch.rand([2,3])
print('x * y =', x*y,'\n\n')
print('z=\n',z,'\n\n')
print('The shape of x = \n',a,'\n\n')
print('Random tensor = \n ',b,'\n\n')


# the application of .view
b = b.view([1,6])
print(b)

x * y = tensor([ 6., 15.]) 


z=
 [[0. 0. 0.]
 [0. 0. 0.]] 


The shape of x = 
 torch.Size([2]) 


Random tensor = 
  tensor([[0.6793, 0.7024, 0.2809],
        [0.1228, 0.4619, 0.8882]]) 


tensor([[0.6793, 0.7024, 0.2809, 0.1228, 0.4619, 0.8882]])
